logLevel: "debug"
logFileName: "pack_go.log"
# 单位为天
logFileMaxAge: 7
# 单位为小时
logFileRotationTime: 1
model: "weights/res10_300x300_ssd_iter_140000_fp16.caffemodel"
proto: "weights/deploy.prototxt.txt"
deviceID: 0
